// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX09mHrYo6ExIHKa0PMwxwa3SsZu_kPE4',
    appId: '1:16898415465:web:d9bb101d4f1183980d7bf8',
    messagingSenderId: '16898415465',
    projectId: 'streamapp-b6fe5',
    authDomain: 'streamapp-b6fe5.firebaseapp.com',
    storageBucket: 'streamapp-b6fe5.firebasestorage.app',
    measurementId: 'G-9V29CJXCEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgpMYjiajblhzCtLU8Qizr7cOUbacF50',
    appId: '1:16898415465:android:39609d353909e4080d7bf8',
    messagingSenderId: '16898415465',
    projectId: 'streamapp-b6fe5',
    storageBucket: 'streamapp-b6fe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcMMnxli99H1je9i0nGQbLErMxl2gLdH0',
    appId: '1:16898415465:ios:11e8d0f70517fb6a0d7bf8',
    messagingSenderId: '16898415465',
    projectId: 'streamapp-b6fe5',
    storageBucket: 'streamapp-b6fe5.firebasestorage.app',
    iosBundleId: 'com.example.streamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcMMnxli99H1je9i0nGQbLErMxl2gLdH0',
    appId: '1:16898415465:ios:11e8d0f70517fb6a0d7bf8',
    messagingSenderId: '16898415465',
    projectId: 'streamapp-b6fe5',
    storageBucket: 'streamapp-b6fe5.firebasestorage.app',
    iosBundleId: 'com.example.streamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX09mHrYo6ExIHKa0PMwxwa3SsZu_kPE4',
    appId: '1:16898415465:web:1e30d461ad52e6000d7bf8',
    messagingSenderId: '16898415465',
    projectId: 'streamapp-b6fe5',
    authDomain: 'streamapp-b6fe5.firebaseapp.com',
    storageBucket: 'streamapp-b6fe5.firebasestorage.app',
    measurementId: 'G-67QG5Z8T0R',
  );
}
